spring:
  application:
    name: blog

  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: your-256-bit-secret-key-here-make-it-at-least-32-bytes-long
  expiration-ms: 86400000